sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="5.4"
    - DOCKERFILE="5.4/apache"
    - DOCKERFILE="5.4/fpm"
    - DOCKERFILE="5.5"
    - DOCKERFILE="5.5/apache"
    - DOCKERFILE="5.5/fpm"
    - DOCKERFILE="5.6"
    - DOCKERFILE="5.6/apache"
    - DOCKERFILE="5.6/fpm"
    - DOCKERFILE="7.0"
    - DOCKERFILE="7.0/apache"
    - DOCKERFILE="7.0/fpm"
    - DOCKERFILE="5.4-alpine"
    - DOCKERFILE="5.4-alpine/fpm"
    - DOCKERFILE="5.5-alpine"
    - DOCKERFILE="5.5-alpine/fpm"
    - DOCKERFILE="5.6-alpine"
    - DOCKERFILE="5.6-alpine/fpm"
    - DOCKERFILE="7.0-alpine"
    - DOCKERFILE="7.0-alpine/fpm"

before_script:
  - docker version

script:
  - docker build -t ${DOCKERFILE} ./${DOCKERFILE}

after_script:
  - docker images
